
development:
  adapter: postgresql
  database: Jslerning
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: Jslerning
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: Jslerning
  pool: 5
  timeout: 5000


